# Generated by Django 4.0.4 on 2022-04-16 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='uses_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='personal_referral',
        ),
        migrations.AddField(
            model_name='referral',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user'),
        ),
    ]
