# Generated by Django 4.0.4 on 2022-04-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_order_finish_at_alter_order_paid_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='finish_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
