# Generated by Django 3.2.13 on 2022-04-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_referral_finish_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='clientname',
            field=models.CharField(max_length=32, unique=True, verbose_name='Nicname'),
        ),
    ]
