# Generated by Django 3.2.13 on 2022-05-04 17:21

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='server_addres',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='referral',
            name='code',
            field=models.CharField(blank=True, default=api.models.gen_code, max_length=30),
        ),
    ]
