# Generated by Django 3.2.13 on 2022-05-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220504_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='peers',
            field=models.ManyToManyField(null=True, related_name='order', to='api.Peer'),
        ),
    ]
