# Generated by Django 3.2.13 on 2022-05-08 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_tariff_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peer',
            name='enabled',
        ),
    ]
