# Generated by Django 3.2.13 on 2022-05-09 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_peer_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral', to='api.user'),
        ),
    ]
