# Generated by Django 3.2.13 on 2022-05-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20220509_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='peers',
            field=models.ManyToManyField(related_name='order', to='api.Peer'),
        ),
    ]
