# Generated by Django 3.2.13 on 2022-05-14 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_order_peers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_subscribed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='peers',
            field=models.ManyToManyField(blank=True, related_name='order', to='api.Peer'),
        ),
    ]
