# Generated by Django 3.2.13 on 2022-05-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_tariff_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='connections_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='traffic_amount',
            field=models.FloatField(),
        ),
    ]
